# Copyright 2017-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.3.1

EAPI=7

CRATES="
addr2line-0.17.0
adler-1.0.2
aho-corasick-0.7.18
ansi_term-0.12.1
async-compression-0.3.14
atty-0.2.14
autocfg-1.1.0
backtrace-0.3.66
base64-0.13.0
bitflags-1.3.2
block-buffer-0.10.2
block-buffer-0.7.3
block-padding-0.1.5
bumpalo-3.10.0
byte-tools-0.3.1
byteorder-1.4.3
bytes-1.2.0
cast-0.3.0
cc-1.0.73
cfg-if-1.0.0
clap-3.2.15
clap_complete-3.2.3
clap_derive-3.2.15
clap_lex-0.2.4
core-foundation-0.9.3
core-foundation-sys-0.8.3
cpufeatures-0.2.2
crc32fast-1.3.2
crypto-common-0.1.6
daggy-0.8.0
digest-0.10.3
digest-0.8.1
dirs-4.0.0
dirs-sys-0.3.7
encoding_rs-0.8.31
failure-0.1.8
failure_derive-0.1.8
fake-simd-0.1.2
fastrand-1.8.0
fixedbitset-0.4.2
flate2-1.0.24
fnv-1.0.7
foreign-types-0.3.2
foreign-types-shared-0.1.1
form_urlencoded-1.0.1
fs_extra-1.2.0
futures-0.3.21
futures-channel-0.3.21
futures-core-0.3.21
futures-executor-0.3.21
futures-io-0.3.21
futures-macro-0.3.21
futures-sink-0.3.21
futures-task-0.3.21
futures-util-0.3.21
generic-array-0.12.4
generic-array-0.14.5
getrandom-0.2.7
gimli-0.26.2
git2-0.15.0
h2-0.3.13
hashbrown-0.12.3
heck-0.4.0
hermit-abi-0.1.19
http-0.2.8
http-body-0.4.5
httparse-1.7.1
httpdate-1.0.2
hyper-0.14.20
hyper-tls-0.5.0
idna-0.2.3
indexmap-1.9.1
instant-0.1.12
ipnet-2.5.0
itoa-1.0.2
jemalloc-sys-0.5.1+5.3.0-patched
jemallocator-0.5.0
jobserver-0.1.24
js-sys-0.3.59
lazy_static-1.4.0
libc-0.2.126
libgit2-sys-0.14.0+1.5.0
libz-sys-1.1.8
linked-hash-map-0.5.6
log-0.4.17
maplit-1.0.2
matches-0.1.9
memchr-2.5.0
mime-0.3.16
miniz_oxide-0.5.3
mio-0.8.4
native-tls-0.2.10
num_cpus-1.13.1
object-0.29.0
once_cell-1.13.0
opaque-debug-0.2.3
openssl-0.10.41
openssl-macros-0.1.0
openssl-probe-0.1.5
openssl-sys-0.9.75
os_str_bytes-6.2.0
percent-encoding-2.1.0
pest-2.1.3
pest_derive-2.1.0
pest_generator-2.1.3
pest_meta-2.1.3
petgraph-0.6.2
pin-project-lite-0.2.9
pin-utils-0.1.0
pkg-config-0.3.25
proc-macro-error-1.0.4
proc-macro-error-attr-1.0.4
proc-macro2-1.0.42
quote-1.0.20
redox_syscall-0.2.16
redox_users-0.4.3
regex-1.6.0
regex-syntax-0.6.27
remove_dir_all-0.5.3
reqwest-0.11.11
rustc-demangle-0.1.21
rustversion-1.0.8
ryu-1.0.10
same-file-1.0.6
schannel-0.1.20
security-framework-2.6.1
security-framework-sys-2.6.1
semver-1.0.12
serde-1.0.140
serde-tuple-vec-map-1.0.1
serde_derive-1.0.140
serde_json-1.0.82
serde_urlencoded-0.7.1
serde_yaml-0.8.26
serde_yaml-0.9.0
sha-1-0.10.0
sha-1-0.8.2
signal-hook-registry-1.4.0
slab-0.4.7
socket2-0.4.4
strsim-0.10.0
strum-0.24.1
strum_macros-0.24.2
syn-1.0.98
synstructure-0.12.6
tempfile-3.3.0
termcolor-1.1.3
terminal_size-0.1.17
textwrap-0.15.0
thiserror-1.0.31
thiserror-impl-1.0.31
tinyvec-1.6.0
tinyvec_macros-0.1.0
tokio-1.20.1
tokio-native-tls-0.3.0
tokio-util-0.7.3
tower-service-0.3.2
tracing-0.1.35
tracing-core-0.1.28
try-lock-0.2.3
typenum-1.15.0
ucd-trie-0.1.4
unicode-bidi-0.3.8
unicode-ident-1.0.2
unicode-normalization-0.1.21
unicode-xid-0.2.3
unsafe-libyaml-0.2.1
url-2.2.2
vcpkg-0.2.15
version_check-0.9.4
walkdir-2.3.2
want-0.3.0
wasi-0.11.0+wasi-snapshot-preview1
wasm-bindgen-0.2.82
wasm-bindgen-backend-0.2.82
wasm-bindgen-futures-0.4.32
wasm-bindgen-macro-0.2.82
wasm-bindgen-macro-support-0.2.82
wasm-bindgen-shared-0.2.82
web-sys-0.3.59
winapi-0.3.9
winapi-i686-pc-windows-gnu-0.4.0
winapi-util-0.1.5
winapi-x86_64-pc-windows-gnu-0.4.0
windows-sys-0.36.1
windows_aarch64_msvc-0.36.1
windows_i686_gnu-0.36.1
windows_i686_msvc-0.36.1
windows_x86_64_gnu-0.36.1
windows_x86_64_msvc-0.36.1
winreg-0.10.1
yaml-merge-keys-0.5.1
yaml-rust-0.4.5
"

inherit cargo bash-completion-r1

MY_PV=$(ver_rs 3 - 4 .)

COMPDIR="${WORKDIR}/completions"
TMPBIN="${S}/target/release/${PN}"
SRCTAR="${PN}-release-${MY_PV}.tar.gz"

DESCRIPTION="General purpose Docker image management tool"
HOMEPAGE="https://github.com/Ultinous/docker-util"
SRC_URI="http://can-i-haz-files/gentoo/${SRCTAR} $(cargo_crate_uris ${CRATES})"

RESTRICT="mirror"

LICENSE="all-rights-reserved"
SLOT="0"
KEYWORDS="amd64 arm64 ~x86 ~arm"
IUSE="bash-completion zsh-completion fish-completion"

DEPEND="
	dev-libs/openssl:=
	dev-libs/libgit2:=
"
RDEPEND="${DEPEND}
	app-containers/docker-cli
"
BDEPEND=">=virtual/rust-1.61.0"

pkg_nofetch() {
	einfo "Please download ${SRCTAR} from ${HOMEPAGE} and place them in your DISTDIR directory."
}

src_prepare() {
	default
	rm -rf ${S}
	mv ${WORKDIR}/${PN}-release-${MY_PV} ${S}
	mkdir ${COMPDIR}
}

src_compile() {
	cargo_src_compile

	use bash-completion &&
		${TMPBIN} completions bash > ${COMPDIR}/bash

	use fish-completion &&
		${TMPBIN} completions fish > ${COMPDIR}/fish

	use zsh-completion &&
		${TMPBIN} completions zsh > ${COMPDIR}/zsh
}

src_install() {
	cargo_src_install

	use bash-completion &&
		newbashcomp ${COMPDIR}/bash ${PN}

	if use fish-completion; then
		insinto /usr/share/fish/completions
		newins ${COMPDIR}/fish ${PN}
	fi

	if use zsh-completion; then
		insinto /usr/share/zsh/site-functions
		newins ${COMPDIR}/zsh _${PN}
	fi
}
